services:

  web-app:
    container_name: web-frontend-e2e-test
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/pwuser/web-app
    volumes:
      - ./web-app:/home/pwuser/web-app
      - node_modules:/home/pwuser/web-app/node_modules
    tty: true

volumes:
  node_modules:
