services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=very-strong-passowrd
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
